version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - net
    environment:
      - MYSQL_ROOT_PASSWORD=mynodeapp
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=mynodeapp
      - MYSQL_PASSWORD=mynodeapp
    ports:
      - 3306:3306
  app:
    depends_on:
      - db
    image: my-node-app
#    build:
#      context: .
#      dockerfile: Dockerfile
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - net
    ports:
      - 8080:3000
    environment:
      - DB_HOST=db:3306
      - DB_USERNAME=mynodeapp
      - DB_PASSWORD=mynodeapp
      - DB_DATABASE=mydb
volumes:
 db_data:
 wordpress_data:

networks:
  net:
    external: true