version: '3.8'
services:
  app:
    image: my-node-app
#    build:
#      context: .
#      dockerfile: Dockerfile
    deploy:
      replicas: 3
      restart_policy:
        condition: any
    ports:
      - 8080:3000
    environment:
      - DB_HOST=db
      - DB_USERNAME=mynodeapp
      - DB_PASSWORD=mynodeapp
      - DB_DATABASE=mydb

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=mynodeapp
      - MYSQL_DATABASE=mydb
    ports:
      - 3306:3306